service: enacom-notes

plugins:
  - serverless-webpack
  - serverless-offline

package:
  artifact: .serverless/enacom-notes.zip

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

environment:
  stage: dev

functions:
  GetAllNotes:
    handler: lambdas/getAllNotes.handler
    role: NotesLambdaRole
    events:
      - http:
          path: notes
          method: get
          # cors: true


resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/lambdaRole.yml)}